// Canonical 66-book table. `id` matches the USFX / Paratext codes used for the
// bundled JSON filenames and the HelloAO API. `aliases` are extra spellings the
// parser accepts (all matched case- and punctuation-insensitively).

export const BOOKS = [
  { id: 'GEN', name: 'Genesis', aliases: ['gen', 'ge', 'gn'] },
  { id: 'EXO', name: 'Exodus', aliases: ['exo', 'ex', 'exod'] },
  { id: 'LEV', name: 'Leviticus', aliases: ['lev', 'le', 'lv'] },
  { id: 'NUM', name: 'Numbers', aliases: ['num', 'nu', 'nm', 'nb'] },
  { id: 'DEU', name: 'Deuteronomy', aliases: ['deu', 'dt', 'deut'] },
  { id: 'JOS', name: 'Joshua', aliases: ['jos', 'jsh', 'josh'] },
  { id: 'JDG', name: 'Judges', aliases: ['jdg', 'jg', 'judg'] },
  { id: 'RUT', name: 'Ruth', aliases: ['rut', 'ru', 'rth'] },
  { id: '1SA', name: '1 Samuel', aliases: ['1sa', '1sam', '1s', 'i sam', 'first samuel'] },
  { id: '2SA', name: '2 Samuel', aliases: ['2sa', '2sam', '2s', 'ii sam', 'second samuel'] },
  { id: '1KI', name: '1 Kings', aliases: ['1ki', '1kgs', '1k', 'i kings', 'first kings'] },
  { id: '2KI', name: '2 Kings', aliases: ['2ki', '2kgs', '2k', 'ii kings', 'second kings'] },
  { id: '1CH', name: '1 Chronicles', aliases: ['1ch', '1chr', '1chron', 'i chron'] },
  { id: '2CH', name: '2 Chronicles', aliases: ['2ch', '2chr', '2chron', 'ii chron'] },
  { id: 'EZR', name: 'Ezra', aliases: ['ezr', 'ez'] },
  { id: 'NEH', name: 'Nehemiah', aliases: ['neh', 'ne'] },
  { id: 'EST', name: 'Esther', aliases: ['est', 'es', 'esth'] },
  { id: 'JOB', name: 'Job', aliases: ['job', 'jb'] },
  { id: 'PSA', name: 'Psalms', aliases: ['psa', 'ps', 'psalm', 'psalms', 'pss', 'pslm'] },
  { id: 'PRO', name: 'Proverbs', aliases: ['pro', 'pr', 'prov', 'prv'] },
  { id: 'ECC', name: 'Ecclesiastes', aliases: ['ecc', 'ec', 'eccl', 'qoh'] },
  { id: 'SNG', name: 'Song of Songs', aliases: ['sng', 'song', 'sos', 'song of solomon', 'song of songs', 'canticles'] },
  { id: 'ISA', name: 'Isaiah', aliases: ['isa', 'is'] },
  { id: 'JER', name: 'Jeremiah', aliases: ['jer', 'je', 'jr'] },
  { id: 'LAM', name: 'Lamentations', aliases: ['lam', 'la'] },
  { id: 'EZK', name: 'Ezekiel', aliases: ['ezk', 'eze', 'ezek', 'ezk'] },
  { id: 'DAN', name: 'Daniel', aliases: ['dan', 'da', 'dn'] },
  { id: 'HOS', name: 'Hosea', aliases: ['hos', 'ho'] },
  { id: 'JOL', name: 'Joel', aliases: ['jol', 'joe', 'jl'] },
  { id: 'AMO', name: 'Amos', aliases: ['amo', 'am'] },
  { id: 'OBA', name: 'Obadiah', aliases: ['oba', 'ob', 'obad'], singleChapter: true },
  { id: 'JON', name: 'Jonah', aliases: ['jon', 'jnh'] },
  { id: 'MIC', name: 'Micah', aliases: ['mic', 'mc'] },
  { id: 'NAM', name: 'Nahum', aliases: ['nam', 'na', 'nah'] },
  { id: 'HAB', name: 'Habakkuk', aliases: ['hab', 'hb'] },
  { id: 'ZEP', name: 'Zephaniah', aliases: ['zep', 'zph', 'zeph'] },
  { id: 'HAG', name: 'Haggai', aliases: ['hag', 'hg'] },
  { id: 'ZEC', name: 'Zechariah', aliases: ['zec', 'zc', 'zech'] },
  { id: 'MAL', name: 'Malachi', aliases: ['mal', 'ml'] },
  { id: 'MAT', name: 'Matthew', aliases: ['mat', 'mt', 'matt'] },
  { id: 'MRK', name: 'Mark', aliases: ['mrk', 'mk', 'mr'] },
  { id: 'LUK', name: 'Luke', aliases: ['luk', 'lk', 'lu'] },
  { id: 'JHN', name: 'John', aliases: ['jhn', 'jn', 'joh'] },
  { id: 'ACT', name: 'Acts', aliases: ['act', 'ac', 'acts'] },
  { id: 'ROM', name: 'Romans', aliases: ['rom', 'ro', 'rm'] },
  { id: '1CO', name: '1 Corinthians', aliases: ['1co', '1cor', 'i cor', 'first corinthians'] },
  { id: '2CO', name: '2 Corinthians', aliases: ['2co', '2cor', 'ii cor', 'second corinthians'] },
  { id: 'GAL', name: 'Galatians', aliases: ['gal', 'ga'] },
  { id: 'EPH', name: 'Ephesians', aliases: ['eph', 'ephes'] },
  { id: 'PHP', name: 'Philippians', aliases: ['php', 'phil', 'pp'] },
  { id: 'COL', name: 'Colossians', aliases: ['col', 'co'] },
  { id: '1TH', name: '1 Thessalonians', aliases: ['1th', '1thess', '1thes', 'i thess'] },
  { id: '2TH', name: '2 Thessalonians', aliases: ['2th', '2thess', '2thes', 'ii thess'] },
  { id: '1TI', name: '1 Timothy', aliases: ['1ti', '1tim', 'i tim', 'first timothy'] },
  { id: '2TI', name: '2 Timothy', aliases: ['2ti', '2tim', 'ii tim', 'second timothy'] },
  { id: 'TIT', name: 'Titus', aliases: ['tit', 'ti'] },
  { id: 'PHM', name: 'Philemon', aliases: ['phm', 'phlm', 'philem'], singleChapter: true },
  { id: 'HEB', name: 'Hebrews', aliases: ['heb', 'hb'] },
  { id: 'JAS', name: 'James', aliases: ['jas', 'jm', 'jms'] },
  { id: '1PE', name: '1 Peter', aliases: ['1pe', '1pet', '1pt', 'i pet'] },
  { id: '2PE', name: '2 Peter', aliases: ['2pe', '2pet', '2pt', 'ii pet'] },
  { id: '1JN', name: '1 John', aliases: ['1jn', '1joh', '1jo', 'i john', 'first john'] },
  { id: '2JN', name: '2 John', aliases: ['2jn', '2joh', '2jo', 'ii john'], singleChapter: true },
  { id: '3JN', name: '3 John', aliases: ['3jn', '3joh', '3jo', 'iii john'], singleChapter: true },
  { id: 'JUD', name: 'Jude', aliases: ['jud', 'jd'], singleChapter: true },
  { id: 'REV', name: 'Revelation', aliases: ['rev', 're', 'rv', 'apocalypse'] }
]

export const BOOK_BY_ID = Object.fromEntries(BOOKS.map((b) => [b.id, b]))
