// After `vite build`: move the HTML shell out of the static assets and into the
// Worker bundle. In production the asset layer serves existing files WITHOUT
// running the Worker (neither run_worker_first nor _headers took effect), so an
// index.html asset would ship with no security headers. Served by the Worker,
// every HTML document gets them. Hashed JS/CSS, icons and bible JSON stay assets.
import { readFileSync, writeFileSync, unlinkSync } from 'node:fs'

const dist = new URL('../dist/', import.meta.url)
const html = readFileSync(new URL('index.html', dist), 'utf-8')
writeFileSync(
  new URL('../cloudflare/src/shell.generated.js', import.meta.url),
  `// GENERATED by scripts/postbuild.mjs from dist/index.html -- do not edit.\nexport const SHELL = ${JSON.stringify(html)}\n`
)
unlinkSync(new URL('index.html', dist))
console.log('shell -> cloudflare/src/shell.generated.js; removed dist/index.html')
