// Security headers, defined once. The Worker adds them to every response it
// generates (API, SPA fallback), and scripts/write-headers.mjs renders the same
// set into public/_headers so the static-asset layer applies them to assets it
// serves without invoking the Worker (index.html at /, icons, manifest, JS/CSS).
// Test headersFile.test.js fails if public/_headers drifts from this module.

// Cloudflare Web Analytics: the beacon script host, and the host it reports to.
export const ANALYTICS = 'https://static.cloudflareinsights.com'
export const ANALYTICS_RUM = 'https://cloudflareinsights.com'
// Cloudflare Turnstile: the widget script + its challenge iframe.
export const TURNSTILE = 'https://challenges.cloudflare.com'

export function securityHeaders() {
  const csp = [
    "default-src 'self'",
    `script-src 'self' ${ANALYTICS} ${TURNSTILE}`,
    `frame-src ${TURNSTILE}`,
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
    "font-src 'self' https://fonts.gstatic.com",
    "img-src 'self' data:",
    // 'self' covers same-origin API + WebSocket; HelloAO is the online-translation
    // fallback; ANALYTICS is the Cloudflare beacon.
    `connect-src 'self' ${ANALYTICS} ${ANALYTICS_RUM} https://bible.helloao.org`,
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
    'upgrade-insecure-requests'
  ].join('; ')
  return {
    'Content-Security-Policy': csp,
    'Strict-Transport-Security': 'max-age=63072000; includeSubDomains',
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'DENY',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'microphone=(self), fullscreen=(self), camera=(), geolocation=()'
  }
}

// Which layer produced a response: 'worker' (set by the Worker's decorate) or
// 'assets' (set by the static-asset layer via _headers). Harmless, and it makes
// "why is this header missing?" answerable from a single curl.
export const SOURCE_HEADER = 'X-OpenLectern-Source'

// The `_headers` file for Workers static assets: one rule for every path.
export function headersFileText() {
  const lines = ['# GENERATED by `npm run build:headers` from cloudflare/src/headers.js -- do not edit.', '/*']
  for (const [k, v] of Object.entries(securityHeaders())) lines.push(`  ${k}: ${v}`)
  lines.push(`  ${SOURCE_HEADER}: assets`)
  return lines.join('\n') + '\n'
}
